--usuwa tabele
DROP TABLE [LIFT_STATUS_CHANGE]
DROP TABLE [STATUS]
DROP TABLE [TICKET_SCAN]

DROP TABLE [JUNK]
DROP TABLE [DATE]
DROP TABLE [TIME]
DROP TABLE LIFT
DROP TABLE SKIPASS

DROP TABLE CLIENT

--usuwa ca³e dane z tabel; Czemu nie dziala? Trzeba by chyba zrobic usuwanie danych kaskadowe
TRUNCATE TABLE [LIFT_STATUS_CHANGE]
TRUNCATE TABLE [STATUS]
TRUNCATE TABLE [TICKET_SCAN]

TRUNCATE TABLE [JUNK]
TRUNCATE TABLE [DATE]
TRUNCATE TABLE [TIME]
TRUNCATE TABLE LIFT
TRUNCATE TABLE SKIPASS

TRUNCATE TABLE CLIENT